name: turmalina_jobs
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_mobx: ^2.3.0
  flutter_modular: ^6.3.3
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  mobx: ^2.5.0
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mocktail: ^1.0.4
  build_runner: ^2.4.9
  mobx_codegen: ^2.7.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/turmalina_jobs_icon.png
    - assets/images/turmalina_jobs_logo.png
    - assets/images/app_turmalina_jobs_background.png

flutter_launcher_icons:
  android: true
  image_path_android: "assets/images/turmalina_jobs_icon.png"
  adaptative_icon_background: "#ffffff"
  adaptative_icon_foreground: "assets/images/procraft_playstore.png"
  min_sdk_android: 16
